import Video1 from "./Videos/coffeevid01.mp4";
import Video2 from "./Videos/coffeevid02.mp4";

import { ReactComponent as Africa } from "./Countries/africaHighspec.svg";
import { ReactComponent as Asia } from "./Countries/asiaHighspec.svg";
import { ReactComponent as SouthAmerica } from "./Countries/southAmericaHighspec.svg";
import Brazil01 from "./CoffeeImgs/Brazil01.png";
import Brazil02 from "./CoffeeImgs/Brazil02.png";
import Brazil03 from "./CoffeeImgs/Brazil03.png";
import Burundi01 from "./CoffeeImgs/Burundi01.png";
import Burundi02 from "./CoffeeImgs/Burundi02.png";
import Burundi03 from "./CoffeeImgs/Burundi03.png";
import Colombia01 from "./CoffeeImgs/Colombia01.png";
import Colombia02 from "./CoffeeImgs/Colombia02.png";
import Colombia03 from "./CoffeeImgs/Colombia03.png";
import CostaRica01 from "./CoffeeImgs/CostaRica01.png";
import CostaRica02 from "./CoffeeImgs/CostaRica02.png";
import CostaRica03 from "./CoffeeImgs/CostaRica03.png";
import Ethiopia01 from "./CoffeeImgs/Ethiopia01.png";
import Ethiopia02 from "./CoffeeImgs/Ethiopia02.png";
import Ethiopia03 from "./CoffeeImgs/Ethiopia03.png";
import Indonesia01 from "./CoffeeImgs/Indonesia01.png";
import Indonesia02 from "./CoffeeImgs/Indonesia02.png";
import Indonesia03 from "./CoffeeImgs/Indonesia03.png";
import Kenya01 from "./CoffeeImgs/Kenya01.png";
import Kenya02 from "./CoffeeImgs/Kenya02.png";
import Kenya03 from "./CoffeeImgs/Kenya03.png";
import Thailand01 from "./CoffeeImgs/Thailand01.png";
import Thailand02 from "./CoffeeImgs/Thailand02.png";
import Thailand03 from "./CoffeeImgs/Thailand03.png";
import Vietnam01 from "./CoffeeImgs/Vietnam01.png";
import Vietnam02 from "./CoffeeImgs/Vietnam02.png";
import Vietnam03 from "./CoffeeImgs/Vietnam03.png";

export const sliderContent = [
  {
    id: 1,
    video: Video1,
  },
  {
    id: 2,
    video: Video2,
  },
];

export const regions = [
  {
    id: 1,
    image: <Africa />,
    title: "Africa",
    info: "Coffee grown worldwide can trace its heritage back centuries to the ancient coffee forests on the Ethiopian plateau. There, legend says the goat herder Kaldi first discovered the potential of these beloved beans.The story goes that that Kaldi discovered coffee after he noticed that after eating the berries from a certain tree, his goats became so energetic that they did not want to sleep at night. Kaldi reported his findings to the abbot of the local monastery, who made a drink with the berries and found that it kept him alert through the long hours of evening prayer. The abbot shared his discovery with the other monks at the monastery, and knowledge of the energizing berries began to spread.",
  },
  {
    id: 2,
    image: <Asia />,
    title: "Asia",
    info: "The history of coffee in Asia, much like the history of coffee in Europe and the Americas, began with a crime. In the early 1600s, a man by the name of Baba Budan who was on a pilgrimage to Mecca stopped for a visit to the Yemeni port city of Mocha, the legendary coffee hub that enabled the delicious drink to reach all across Arabia. Hoping to bring the delicious drink with him, Baba Budan smuggled six coffee beans by taping them on to his stomach. After a long journey back to India, Baba Budan planted the coffee beans in the quaint hill town of Chikamagalur, Karnataka. In fact, coffee was so popular that it was being cultivated even before tea. The coffee plant had already established itself as a commercial crop in India by the 19th century and was being exported to Europe. The dense jungles of the West Ghat mountains enabled the growth of arabica and robusta coffee under the shade, which helped contribute to the coffee plant’s unique flavor.",
  },
  {
    id: 3,
    image: <SouthAmerica />,
    title: "SouthAmerica",
    info: "A coffee tree presented to Louis XIV by the Dutch in 1715 and nurtured in Paris's Royal Botanical Garden would make an indelible mark on coffee's history with the help of a resolute French naval officer. On leave from Martinique in 1720, Gabriel Mathieu de Clieu was convinced that Martinique could become as successful a coffee producer as Java. When his request for a coffee plant grown from the king's noble tree was summarily denied, de Clieu staged a late night raid on the Royal Garden to secure one of the plants himself. Although de Clieu's daring effort was successful, it actually proved less harrowing than his perilous transatlantic return to Martinique, as he was compelled to share his meager water rations with the fledgling tree. But within 50 years of the plant's arrival on Martinique, de Clieu's heroics literally bore fruit. The confiscated plant yielded over 18,000 coffee trees. Much of the world's coffee, including the majority of the coffee destined for cultivation in the Americas, is descended from that single tree.",
  },
];

export const products = [
  {
    id: 1,
    Brand: "Barbarossa",
    country: "Ethiopia",
    region: "Africa",
    image: Ethiopia01,
    name: "Sidamo Coffee",
    size: "100g",
    roastLevel: "Light Roast",
    flavourProfile: " Sweet Fruity",
    price: "¥2500",
  },
  {
    id: 2,
    Brand: "Barbarossa",
    country: "Ethiopia",
    region: "Africa",
    image: Ethiopia02,
    name: "Yiragacheffe coffee",
    size: "100g",
    roastLevel: "Light-Medium",
    flavourProfile: "Sweet Floral",
    price: "¥2500",
  },
  {
    id: 3,
    Brand: "Barbarossa",
    country: "Ethiopia",
    region: "Africa",
    image: Ethiopia03,
    name: "Limu Coffee",
    size: "100g",
    roastLevel: "Medium-Light",
    flavourProfile: "Floral, Citrus, Green Tea",
    price: "¥2500",
  },
  {
    id: 4,
    brand: "Barbarossa",
    country: "Burundi",
    region: "Africa",
    image: Burundi01,
    name: "Kayanze Coffee",
    size: "100g",
    roastLevel: "Medium-Dark",
    flavourProfile: "Jasmin Hibiscus",
    price: "¥2500",
  },
  {
    id: 5,
    brand: "GiacoBean",
    country: "Burundi",
    region: "Africa",
    image: Burundi02,
    name: "Burundi Single Origin",
    size: "100g",
    roastLevel: "Medium",
    flavourProfile: "juicy fruits, honey, molasses, caramel",
    price: "¥2500",
  },
  {
    id: 6,
    brand: "Takelma",
    country: "Burundi",
    region: "Africa",
    image: Burundi03,
    name: "Aàytaʼxi",
    size: "100g",
    roastLevel: "Medium/Light Roast",
    flavourProfile: "Fig, Stone Fruit, Date",
    price: "¥2500",
  },
  {
    id: 7,
    brand: "Alpha",
    country: "Kenya",
    region: "Africa",
    image: Kenya01,
    name: " Kianderi Station",
    size: "100g",
    roastLevel: "Light",
    flavourProfile: "Black Tea and Lemon.",
    price: "¥2500",
  },
  {
    id: 8,
    brand: "Julius Meinl am Graben",
    country: "Kenya",
    region: "Africa",
    image: Kenya02,
    name: "Single Origin Kenya whole bean",
    size: "100g",
    roastLevel: "Strong roast",
    flavourProfile: "Dark caramel envelops dried plums.",
    price: "¥2500",
  },
  {
    id: 9,
    brand: "Coffee Bros.",
    country: "Kenya",
    region: "Africa",
    image: Kenya03,
    name: "Kenya AA",
    size: "100g",
    roastLevel: "Light to Medium Roast",
    flavourProfile: "Sugary Plum, Chocolate, Lemon",
    price: "¥2500",
  },
  {
    id: 10,
    Brand: "Campos",
    country: "Indonesia",
    region: "Asia",
    image: Indonesia01,
    name: "INDONESIA FRINSA",
    size: "100g",
    roastLevel: " Medium Roast",
    flavourProfile:
      "Sweet like Cherry Pie. Flavours like Mulled Wine & Guava. ",
    price: "¥2500",
  },
  {
    id: 11,
    Brand: "Stone Street",
    country: "Indonesia",
    region: "Asia",
    image: Indonesia02,
    name: "SUMATRA MANDHELING",
    size: "100g",
    roastLevel: "Dark roast",
    flavourProfile: "chocolate, cedar, sweet tobacco, and spice.",
    price: "¥2500",
  },
  {
    id: 12,
    Brand: "Stone Street",
    country: "Indonesia",
    region: "Asia",
    image: Indonesia03,
    name: "SUMATRA GAYO",
    size: "100g",
    roastLevel: "Dark roast",
    flavourProfile: "chocolate, stone fruit, and tropical fruit.",
    price: "¥2500",
  },
  {
    id: 13,
    brand: "Nguyen",
    country: "Vietnam",
    region: "Asia",
    image: Vietnam01,
    name: "HANOI (100% ROBUSTA)",
    size: "100g",
    roastLevel: "Dark",
    flavourProfile: "Tobacco, Prunes, Graham Cracker",
    price: "¥2500",
  },
  {
    id: 14,
    brand: "Nguyen",
    country: "Vietnam",
    region: "Asia",
    image: Vietnam02,
    name: "100% Single Origin Peaberry Robusta",
    size: "100g",
    roastLevel: "Medium",
    flavourProfile: "Scotch, Grapefruit Zest, Bitter Melon",
    price: "¥2500",
  },
  {
    id: 15,
    brand: "Nguyen",
    country: "Vietnam",
    region: "Asia",
    image: Vietnam03,
    name: "MOXY (100% ARABICA)",
    size: "100g",
    roastLevel: "Medium",
    flavourProfile: "Wild Berries, Chocolate, Cherry, Honey",
    price: "¥2500",
  },
  {
    id: 16,
    brand: "Old Quater",
    country: "Thailand",
    region: "Asia",
    image: Thailand01,
    name: " THAILAND AKHA",
    size: "100g",
    roastLevel: "Espresso Roast",
    flavourProfile: "Caramel Syrup, Fudge, Cranberry",
    price: "¥2500",
  },
  {
    id: 17,
    brand: "Old Quater",
    country: "Thailand",
    region: "Asia",
    image: Thailand02,
    name: "THAILAND - HUAI MAE LIAM (FILTER ROAST)",
    size: "100g",
    roastLevel: "Light Roast",
    flavourProfile: "Strawberry, White Chocolate, Lychee.",
    price: "¥2500",
  },
  {
    id: 18,
    brand: "Càphê Roasters",
    country: "Thailand",
    region: "Asia",
    image: Thailand03,
    name: "Thailand Single Origin",
    size: "100g",
    roastLevel: "Sugary Plum, Chocolate, Lemon",
    flavourProfile: "Cocoa ,Peanut Butter , Cloves",
    price: "¥2500",
  },
  {
    id: 19,
    Brand: "Thrive Coffee",
    country: "Brazil",
    region: "South America",
    image: Brazil01,
    name: "Brazil - Single Origin Coffee",
    size: "100g",
    roastLevel: "Medium",
    flavourProfile: " Roasted Almonds, Caramel, Dark Chocolate",
    price: "¥2500",
  },
  {
    id: 20,
    Brand: "SEVEN GRAMS CAFFÉ",
    country: "Brazil",
    region: "South America",
    image: Brazil02,
    name: "BRAZIL SINGLE ORIGIN",
    size: "100g",
    roastLevel: "Light",
    flavourProfile: "Chocolatey, nutty, low acidity",
    price: "¥2500",
  },
  {
    id: 21,
    Brand: "Lion Head Beans",
    country: "Brazil",
    region: "South America",
    image: Brazil03,
    name: "Brazil Minas Natural Espresso Coffee Beans Single Origin ",
    size: "100g",
    roastLevel: "Espresso Roast",
    flavourProfile:
      "Roasted almonds, chocolate fudge & dried fruits. Round body with a caramel aftertaste.",
    price: "¥2500",
  },
  {
    id: 22,
    brand: "Bones Coffee",
    country: "Colombia",
    region: "South America",
    image: Colombia01,
    name: "Colombia Single-Origin Colombia Single-Origin",
    size: "100g",
    roastLevel: "Medium",
    flavourProfile: "Cocoa, Green Apple, Nutty ",
    price: "¥2500",
  },
  {
    id: 23,
    brand: "Moreish Coffee Roasters",
    country: "Colombia",
    region: "South America",
    image: Colombia02,
    name: "COLOMBIAN HUILA - SINGLE ORIGIN",
    size: "100g",
    roastLevel: "Medium",
    flavourProfile: " dark chocolate, blackcurrant and citrus peels",
    price: "¥2500",
  },
  {
    id: 24,
    brand: "GENERAL WARFIELD’S COFFEE.",
    country: "Colombia",
    region: "South America",
    image: Colombia03,
    name: "100% ARABICA SINGLE ORIGIN COFFEE - COLOMBIA",
    size: "100g",
    roastLevel: "Medium Roast",
    flavourProfile: "Brazil nut, Grapefruit, Oak",
    price: "¥2500",
  },
  {
    id: 25,
    brand: "Cafe Britt",
    country: "Costa Rica",
    region: "South America",
    image: CostaRica01,
    name: " COSTA RICAN MONTECIELO GOURMET COFFEE FROM TARRAZÚ",
    size: "100g",
    roastLevel: "Medium-Dark",
    flavourProfile: "Chocolate, Grapefruit",
    price: "¥2500",
  },
  {
    id: 26,
    brand: "Cafe Britt",
    country: "Costa Rica",
    region: "South America",
    image: CostaRica02,
    name: "COSTA RICAN TRES RIOS VALDIVIA COFFEE",
    size: "100g",
    roastLevel: "Medium",
    flavourProfile: "Allspice, Orange Citrus, Plum",
    price: "¥2500",
  },
  {
    id: 27,
    brand: "Cafe Britt",
    country: "Costa Rica",
    region: "South America",
    image: CostaRica03,
    name: "COSTA RICAN POAS TIERRA VOLCANICA COFFEE",
    size: "100g",
    roastLevel: "Medium",
    flavourProfile: "Floral, Fresh Soil, Lemon",
    price: "¥2500",
  },
];
